/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminView: typeof import('./src/components/admin/AdminView.vue')['default']
    CinemaInfo: typeof import('./src/components/manager/CinemaManage/CinemaInfo.vue')['default']
    CinemaManage: typeof import('./src/components/manager/CinemaManage/CinemaManage.vue')['default']
    CustomerMenu: typeof import('./src/components/CustomerMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    ManagerMenu: typeof import('./src/components/ManagerMenu.vue')['default']
    ManagerView: typeof import('./src/components/manager/ManagerView.vue')['default']
    MovieCard: typeof import('./src/components/customer/movie/MovieCard.vue')['default']
    MovieDetailPage: typeof import('./src/components/customer/movie/MovieDetailPage.vue')['default']
    MovieManage: typeof import('./src/components/manager/MovieManage/MovieManage.vue')['default']
    RegisterPage: typeof import('./src/components/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffManage: typeof import('./src/components/manager/StaffManage/StaffManage.vue')['default']
    TopBar: typeof import('./src/components/manager/TopBar.vue')['default']
  }
}
